#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.13"
# dependencies = []
# ///
"""Regenerate the Harness sheet: every ribbon, conductor by conductor.

The schematic cannot draw a cable, so this sheet is the cable: for each
ribbon (connectors sharing an ``Interconnect`` field) a table of pin,
net, and what sits at each end, read from the exported netlist.  The
whole sheet is generated; the root sheet only holds its sheet symbol.

Usage:
    tools/gen_harness.py                 # exports the netlist via kicad-cli
    tools/gen_harness.py --netlist x.net
"""

import argparse
import os
import re
import sys
import uuid

from power_model import KI, export_netlist, parse_netlist

SHEET_FILE = os.path.join(KI, "harness.kicad_sch")
ROOT_FILE = os.path.join(KI, "tbox.kicad_sch")
NS = uuid.UUID("5d2c7b1e-8f3a-4c9d-a1e2-6b7c8d9e0f11")
FILE_UUID = str(uuid.uuid5(NS, "file"))
SHEET_UUID = str(uuid.uuid5(NS, "sheet"))
ROOT_UUID = "6a29b3f1-3e67-482d-942d-4557fa8bc2d6"
PAGE = "41"


def board_of(comp):
    parts = comp["sheet"].strip("/").split("/")
    return parts[0] if parts and parts[0] else "Root"


def short(net):
    return net.split("/")[-1] if net.startswith("/") else net


def text(s, x, y, size=1.27, bold=False, key=None):
    b = " (bold yes)" if bold else ""
    esc = s.replace("\\", "\\\\").replace('"', '\\"')
    uid = uuid.uuid5(NS, key or f"t:{x}:{y}:{s}")
    return (
        f'  (text "{esc}" (exclude_from_sim no) (at {x:g} {y:g} 0)'
        f' (effects (font (size {size} {size}){b}) (justify left bottom)) (uuid "{uid}"))'
    )


def main():
    ap = argparse.ArgumentParser(description="Regenerate the TBox harness sheet.")
    ap.add_argument("--netlist")
    args = ap.parse_args()
    with open(args.netlist or export_netlist()) as f:
        netlist = f.read()
    comps, _touches = parse_netlist(netlist)

    cables = {}
    for ref, c in comps.items():
        tag = c["fields"].get("Interconnect")
        if tag:
            cables.setdefault(tag, []).append(ref)
    pin_net = {}
    for net, body in re.findall(
        r'\(net\s+\(code\s+"[^"]*"\)\s+\(name\s+"([^"]*)"\)(.*?)(?=\(net\s+\(code|\Z)',
        netlist,
        re.DOTALL,
    ):
        for ref, pin in re.findall(
            r'\(node\s+\(ref\s+"([^"]+)"\)\s+\(pin\s+"([^"]+)"\)', body
        ):
            pin_net[(ref, pin)] = net

    lines = [
        "(kicad_sch",
        "  (version 20250114)",
        '  (generator "eeschema")',
        '  (generator_version "9.0")',
        f'  (uuid "{FILE_UUID}")',
        '  (paper "A4")',
        '  (title_block (title "TBox — Harness") (rev "0.2") (company "TBox"))',
        "  (lib_symbols)",
        text(
            "HARNESS  (generated by tools/gen_harness.py from the netlist -- do not hand-edit)",
            20.32,
            20.32,
            1.778,
            True,
        ),
        text(
            'Each ribbon is straight-through 0.1" IDC; pin n at one end is pin n at the other. Power rails ride the same cable as the signals.',
            20.32,
            24.13,
        ),
        text(
            "GND conductors are placed between signals on purpose; keep the pin order when re-crimping.",
            20.32,
            26.67,
        ),
    ]
    x0, y = 20.32, 38.1
    for tag, refs in sorted(cables.items()):
        a, b = sorted(refs, key=lambda r: board_of(comps[r]))
        npins = max(int(p) for (r, p) in pin_net if r == a)
        lines.append(
            text(
                f"Ribbon {tag}: {a} ({board_of(comps[a])})  <->  {b} ({board_of(comps[b])}), {npins} way",
                x0,
                y,
                1.5,
                True,
            )
        )
        y += 3.81
        for col in (0, 1):
            cx = x0 + 45.72 * col
            lines.append(text("pin", cx, y, 1.27))
            lines.append(text("net", cx + 8.89, y, 1.27))
        y += 2.54
        for k in range(1, npins + 1, 2):
            for col, kk in enumerate((k, k + 1)):
                cx = x0 + 45.72 * col
                net = pin_net.get((a, str(kk)))
                name = (
                    "n/c"
                    if net is None or net.startswith("unconnected-")
                    else short(net)
                )
                lines.append(text(f"{kk:>2}", cx, y, 1.27))
                lines.append(text(name, cx + 8.89, y, 1.27))
            y += 2.54
        y += 6.35
    lines.append(")")
    with open(SHEET_FILE, "w") as f:
        f.write("\n".join(lines) + "\n")

    # sheet symbol on the root, once
    with open(ROOT_FILE) as f:
        root = f.read()
    if SHEET_UUID not in root:
        blk = (
            "  (sheet (at 90.17 165.1) (size 50.8 20.32)\n"
            "    (stroke (width 0.1524) (type solid)) (fill (color 0 0 0 0.0))\n"
            f'    (uuid "{SHEET_UUID}")\n'
            '    (property "Sheetname" "Harness" (at 90.17 161.6 0) (effects (font (size 1.27 1.27)) (justify left bottom)))\n'
            '    (property "Sheetfile" "harness.kicad_sch" (at 90.17 164.1 0) (effects (font (size 1.27 1.27)) (justify left bottom)))\n'
            f'    (instances (project "tbox" (path "/{ROOT_UUID}" (page "{PAGE}"))))\n'
            "  )"
        )
        root = root.rstrip()[:-1].rstrip("\n") + "\n" + blk + "\n)\n"
        with open(ROOT_FILE, "w") as f:
            f.write(root)
        print("harness sheet symbol added to the root")
    print(f"harness: {len(cables)} ribbon(s) -> harness.kicad_sch")
    return 0


if __name__ == "__main__":
    sys.exit(main())
